---
# tasks file for epel

- name: Autodetect EPEL URL
  epel_facts:
    distribution: "{{ ansible_distribution }}"
    major_version: "{{ ansible_distribution_major_version }}"
    architecture: "{{ ansible_architecture }}"
  delegate_to: localhost
  register: epel_facts
  tags:
    - epel
    - repos

- name: debug output (epel_facts)
  debug:
    var: epel_facts
    verbosity: 1
  tags:
    - epel
    - repos

- name: Setup EPEL repo
  when: epel_facts.has_epel | bool
  block:

    - name: Ensure EPEL is configured
      yum_repository:
        name: epel
        description: Extra Packages for Enterprise Linux
        baseurl: "{{ epel_facts.url }}"
        gpgkey: "{{ epel_facts.gpg_url }}"
        enabled: "{{ epel_enabled | bool }}"
        gpgcheck: "{{ epel_facts.has_gpg | bool }}"
        exclude: "{{ epel_exclude }}"
      tags:
        - epel
        - repos

    - name: Import EPEL GPG key
      rpm_key:
        key: "{{ epel_facts.gpg_url }}"
        state: present
      tags:
        - epel
        - repos
