---
# tasks file for tower

- include_tasks: install.yml

- include_tasks: ssl_certs.yml

- include_tasks: license.yml

- name: ensure required directories exist in AWX home
  file:
    state: directory
    path: "/var/lib/awx/{{ item }}"
    owner: awx
    group: awx
    mode: 0750
  loop:
    - .config
    - .local
    - .local/share
  tags:
    - tower
    - filesystem
