#!/usr/bin/ansible-playbook
---
- name: patch infrastructure (dhcp/dns/postfix) servers
  hosts: all
  become: yes
  gather_facts: no
  serial: 1
  any_errors_fatal: yes

  tasks:
    - include_role: 
        name: lock
      vars:
        lock_name: patching
        lock_state: acquired
        lock_permanent: Yes

    - name: check for updates
      yum:
        name: '*'
        state: latest
      check_mode: yes
      register: yum_check

    - name: patch the server
      when: yum_check is changed
      block:
      - name: remove node from cluster
        service:
          name: keepalived
          state: stopped

      - name: update all packages
        yum:
          name: '*'
          state: latest
      
      - name: reboot the server
        reboot:

      - name: check all services
        service:
          name: "{{ item }}"
          state: started
          enabled: yes
        loop:
          - keepalived
          - postfix
          - named
          - dhcpd

      - name: ensure dns is working
        shell: /usr/bin/dig +time=1 +tries=1 @localhost www.google.com

    - include_role: 
        name: lock
      vars:
        lock_name: patching
        lock_state: released
        lock_permanent: Yes