#!/usr/bin/ansible-playbook -e @secrets.yml -i hosts/foreman.py
---

- import_playbook: elevate_foreman_params.yaml

- name: core configuration to all hosts
  hosts: "{{ chain_limit | default('all:!foreman_hostcollection_appliances') }}"
  become: yes
  become_user: root

  roles:
    - common
    - ansible-deps
    - role: root-user
      root_user_s3_keys_bucket: "{{ aws_keys_bucket }}"
      root_user_s3_access_key: "{{ aws_access_key | default(omit) }}"
      root_user_s3_secret_key: "{{ aws_secret_key | default(omit) }}"
    - role: ntp
      ntp_servers:
        - "{{ foreman_params['ntp-server'] }}"
    - role: postfix
      postfix_mynetworks: "{{ foreman_params['postfix_mynetworks'] }}"
      postfix_myorigin: "{{ foreman_params['postfix_myorigin'] }}"
      postfix_relayhost: "{{ foreman_params['postfix_relayhost'] }}"
      postfix_inet_interfaces: "{{ foreman_params['postfix_inet_interfaces'] | default('127.0.0.1') }}"
      postfix_sasl_auth_enable: "{{ foreman_params['postfix_sasl_auth_enable'] | default(False) }}"
      postfix_sasl_auth: "{{ foreman_params['postfix_sasl_auth'] | default(omit) }}"
      postfix_sasl_server: "{{ foreman_params['postfix_sasl_server'] | default(omit) }}"
    - role: ssh
      ssh_banner: "{{ foreman_params['ssh_banner'] }}"
    - role: redhatinsights.insights-client
      tags:
        - redhatinsights.insights-client
      when: ansible_distribution == 'RedHat'

